# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'SimpleFavorites' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SimpleFavorites
  pod 'RealmSwift'

  target 'SimpleFavoritesTests' do
    inherit! :search_paths

    # Pods for testing
    pod 'RealmSwift'

  end

  target 'SimpleFavoritesUITests' do
    inherit! :search_paths
    # Pods for testing

  end

end
